#!/bin/bash

# Define a function to install packages on macOS
install_macos() {
  echo "Installing packages on macOS..."
  brew install starship || { echo "Error installing starship"; exit 1; }
  brew install zsh || { echo "Error installing zsh"; exit 1; }
  brew install ripgrep || { echo "Error installing ripgrep"; exit 1; }
  brew install lazygit || { echo "Error installing lazygit"; exit 1; }
  brew install tmux || { echo "Error installing tmux"; exit 1; }
  brew install neovim || { echo "Error installing neovim"; exit 1; }
  brew install zoxide || { echo "Error installing zoxide"; exit 1; }
  brew install fzf || { echo "Error installing fzf"; exit 1; }
}

# Define a function to install packages on Ubuntu/Fedora
install_ubuntu_fedora() {
  echo "Installing packages on Ubuntu/Fedora..."
  # Install starship
  if ! command -v starship &> /dev/null; then
    curl -sS https://starship.rs/install.sh | sh || { echo "Error installing starship"; exit 1; }
  fi

  # Install apt packages
  sudo apt update || { echo "Error updating apt"; exit 1; }
  sudo apt install -y zsh ripgrep || { echo "Error installing zsh and ripgrep"; exit 1; }

  # Install lazygit
  if ! command -v lazygit &> /dev/null; then
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz" || { echo "Error downloading lazygit"; exit 1; }
    tar xf lazygit.tar.gz lazygit || { echo "Error extracting lazygit"; exit 1; }
    sudo install lazygit /usr/local/bin || { echo "Error installing lazygit"; exit 1; }
    rm lazygit.tar.gz lazygit || { echo "Error cleaning up lazygit files"; exit 1; }
  fi

  # Install tmux
  if ! command -v tmux &> /dev/null; then
    sudo apt install -y tmux || { echo "Error installing tmux"; exit 1; }
  fi

  # Install neovim
  if ! command -v nvim &> /dev/null; then
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz || { echo "Error downloading neovim"; exit 1; }
    sudo tar -C /opt -xzf nvim-linux64.tar.gz || { echo "Error extracting neovim"; exit 1; }
    sudo ln -s /opt/nvim-linux64/bin/nvim /usr/local/bin/nvim || { echo "Error linking neovim"; exit 1; }
    rm nvim-linux64.tar.gz
  fi

  # Install zoxide
  if ! command -v zoxide &> /dev/null; then
    curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh || { echo "Error installing tmux"; exit 1; }
  fi
  #
  # Install fzf
  if ! command -v fzf &> /dev/null; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
  fi
}

# Check the operating system and install packages accordingly
if [[ "$OSTYPE" == "darwin"* ]]; then
  install_macos
elif [[ $(grep -E "^(ID|NAME)=" /etc/os-release | grep -Eq "ubuntu|fedora")$? == 0 ]]; then
  install_ubuntu_fedora
else
  echo "Unsupported operating system"
  exit 1
fi

# Change the default shell to zsh
chsh -s $(which zsh) || { echo "Error changing default shell"; exit 1; }
